from abc import ABC, abstractmethod
from collections.abc import Sequence
from datetime import datetime

from stop_loss.domain.enums import DataType
from stop_loss.domain.models import IngestionRun, NormalizedRecord


class RecordRepository(ABC):
    """Abstract interface defining storage and retrieval contracts for StopLoss records."""

    @abstractmethod
    def initialize(self) -> None:
        """Create required tables, indexes, and schema migrations."""

    @abstractmethod
    def upsert_record(self, record: NormalizedRecord) -> None:
        """Insert or update a single normalized record by its record_id."""

    @abstractmethod
    def bulk_upsert_records(self, records: Sequence[NormalizedRecord]) -> int:
        """Atomically insert or update multiple normalized records.

        Returns:
            The count of records successfully persisted.
        """

    @abstractmethod
    def get_record_by_id(self, record_id: str) -> NormalizedRecord | None:
        """Fetch a single record by unique record_id."""

    @abstractmethod
    def get_records_by_type(self, data_type: DataType, limit: int = 100) -> list[NormalizedRecord]:
        """Fetch records filtered by domain DataType."""

    @abstractmethod
    def get_records_by_provider(self, provider: str, limit: int = 100) -> list[NormalizedRecord]:
        """Fetch records generated by a specific provider origin."""

    @abstractmethod
    def get_records_by_entity_or_ticker(
        self, query: str, limit: int = 100
    ) -> list[NormalizedRecord]:
        """Fetch records matching an asset ticker (e.g. XOM) or named entity."""

    @abstractmethod
    def get_records_by_time_range(
        self, start: datetime, end: datetime, limit: int = 100
    ) -> list[NormalizedRecord]:
        """Fetch records where observed_at falls within [start, end]."""

    @abstractmethod
    def search_records(self, query: str, limit: int = 100) -> list[NormalizedRecord]:
        """Full-text or pattern search over indicator, text_value, and metadata."""

    @abstractmethod
    def save_ingestion_run(self, run: IngestionRun) -> None:
        """Persist or update an ingestion run execution log."""

    @abstractmethod
    def list_recent_ingestion_runs(self, limit: int = 20) -> list[IngestionRun]:
        """Retrieve the most recent ingestion runs ordered by started_at descending."""
